name: release

on:
    push:
        tags:
            - '**'

env:
    CARGO_TERM_COLOR: always

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - name: Install Ubuntu dependencies
              run: |
                  sudo DEBIAN_FRONTEND=noninteractive apt-get update
                  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libdbus-1-dev pkg-config

            - name: Build
              run: |
                  cargo build --release

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: target/release/mpris-stop-after-current
